### ISSUE TITLE
Welcome, do this to confirm your access

### ISSUE THREAD

**Issue by stklik** [unige-pinfo-2019/PInfo2#1]
Hello,

Every project member should do the following:
 - ensure that you have access to the repository (read/write) by adding information to the README (clone, change file, commit, push). Make sure to resolve any potential conflicts.
 - reply here after to indicate that everything worked fine 

The finished README file should provide information about your team (team name, project members)

The project leader should close this issue after **every** member replied.

PS: Don't forget to come up with an interesting project. If you really need slides, keep it short (3 slides max)

**Comment by razureladrien** [comment]
I pushed on README and everything worked_

**Comment by CorentinBT** [comment]
Same ^

**Comment by bigotromain** [comment]
Worked well

**Comment by suxlelo** [comment]
same here

**Comment by CorentinBT** [comment]
@fourastiemarvin hop hop hop

**Comment by fourastiemarvin** [comment]
worked from everyone, README updated 
close the issue

**Comment by lutzilutz** [comment]
Quelque chose
