### ISSUE TITLE
Ad display

### ISSUE THREAD

**Issue by razureladrien** [unige-pinfo-2019/PInfo2#15]
Ad with more than 1 image doesn't display correctly

**Comment by lutzilutz** [comment]
Can you point out the faulty commit ?

**Comment by lutzilutz** [comment]
Faulty line : category.service.ts line 136
`
return this.categoryList.find(
`
Called from single-post-view.component.ts line 27
`
this.categoryName = this.categoryService.getCategoryName(this.monPost.categoryId);
`
