### ISSUE TITLE
Your deployment server is ready

### ISSUE THREAD

**Issue by stklik** [unige-pinfo-2019/PInfo2#2]
Dear project members,

your server which you can use as a deployment target is ready.
Please everybody `ssh` into ~~`pinfo2.unige.sh`~~`pinfo2.unige.ch` and assert that you can log in.

@CorentinBT you have been declared Sysadmin. 
You should additionally verify if you have `sudo` access to avoid problems later on.

**PS**: It is up to the Project Manager to make sure everybody follows the instructions and close this issue when not needed any more.

**Comment by stklik** [comment]
I made a mistake. Please note that the updated server address (see OP above)

**Comment by CorentinBT** [comment]
Can't log in, Infinite loading for me.

**Comment by stklik** [comment]
okay thx for testing, we can go and see Nicolas Mayencourt tomorrow who is managing the VMs

**Comment by CorentinBT** [comment]
@stklik Working now.

**Comment by fourastiemarvin** [comment]
@suxlelo @lutzilutz is it done for you?
 tuto: http://www.hostettler.net/2019/02/17/microservice-architecture-part-1.html
