### ISSUE TITLE
Travis CI activation

### ISSUE THREAD

**Issue by CorentinBT** [unige-pinfo-2019/PInfo2#3]
@stklik is it possible to add me as admin for this repo so that I can enable Travis integration. Thank you.

**Comment by stklik** [comment]
I enabled it globally, I think.

**Comment by CorentinBT** [comment]
@stklik I can't turn on the Legacy Service Integration for this repo on Travis CI website.

**Comment by stklik** [comment]
Gave you admin access. Please check

**Comment by CorentinBT** [comment]
@stklik Yep it works waiting for your sonarcloud approval now.

**Comment by stklik** [comment]
Done

**Comment by stklik** [comment]
Please check now... Just saw that they required a second approval

**Comment by CorentinBT** [comment]
@stklik I doesn't appear on my sonarcloud main page I don't know why.

**Comment by stklik** [comment]
OK, let's check on Friday
