### ISSUE TITLE
Increase disk space for pinfo2.unige.ch

### ISSUE THREAD

**Issue by CorentinBT** [unige-pinfo-2019/PInfo2#8]
@stklik Is it possible to increase the disk space for the server `pinfo2.unige.ch` since all docker images barely fit on the disk and we have problems with elasticsearch not being able to index new items because of that.

**Comment by stklik** [comment]
I think it should be. Please go and see Nicolas Mayencourt (2nd floor), who is providing the machines. He can help you out.

**Comment by CorentinBT** [comment]
@stklik Nicolas Mayencourt is not here until Monday so we will not be able to run our project on the server. Is it a problem?

**Comment by stklik** [comment]
It's not ideal, but shouldn't also be too big of a problem.
Make sure that you can show us your application on another machine (e.g. your laptop) instead
